name: restaurant-app-behrain
type: "php:7.4"
runtime:
  extensions:
    - sodium
    - gd
    - exif
web:
  locations:
    "/":
      root: web
      index:
        - install
      allow: true
      passthru: "/install/install.php"
      headers:
        X-FrameOptions: SAMEORIGIN
        X-XSS-Protection: "1; mode=block"
        X-Content-Type-Options: nosniff
      rules:
        \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
          allow: true
        ^/robots\.txt$:
          allow: true

relationships:
  database: "database:mysql"
disk: 2048
mounts:
  "/install": "shared:files/install"
  "app/media":
    source: service
    service: files
    source_path: media
hooks:
  build: |
    curl -fsS https://platform.sh/cli/installer | php
    ln -s ~/install /install

variables:
  php:
    memory_limit: "1024M"
    date.timezone: "Europe/Stockholm"
