name: restaurant-app-behrain
type: "php:7.4"
runtime:
  extensions:
    - sodium
    - gd
    - exif
build:
  flavor: composer
dependencies:
  nodejs:
    n: "*"
web:
  locations:
    "/":
      root: "public"
      index:
        - install/install.php
      allow: true
      passthru: "/install/install.php"
      headers:
        X-XSS-Protection: "1; mode=block"
        X-Content-Type-Options: nosniff
        Access-Control-Allow-Methods: GET
        X-Frame-Options: deny
        Content-Security-Policy: frame-ancestors 'self'
        Referrer-Policy: strict-origin-when-cross-origin
        Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()
      rules:
        \.(jpg|jpeg|png|doc|docx|pdf)$:
          headers:
            Content-Disposition: attachment

relationships:
  database: "database:mysql"
disk: 2048
mounts:
  "/install": "shared:/install"
hooks:
  build: |
    curl -fsS https://platform.sh/cli/installer | php
    ln -s ~/install /install

variables:
  php:
    memory_limit: "1024M"
    date.timezone: "Europe/Stockholm"
  env:
    APP_NAME: Bakgrundsanalys
