name: restaurant-app-behrain
type: "php:7.4"
runtime:
  extensions:
    - sodium
    - gd
    - exif
web:
  locations:
    "/":
      root: web
      index:
        - install
      passthru: "/install/install.php"

relationships:
  database: "database:mysql"
disk: 2048
mounts:
  "/install": "shared:files/install"
  "app/media":
    source: service
    service: files
    source_path: media
hooks:
  build: |
    curl -fsS https://platform.sh/cli/installer | php
    ln -s ~/install /install

variables:
  php:
    memory_limit: "2048M"
    max_execution_time: 600
    date.timezone: "Europe/Stockholm"
